### ISSUE TITLE
InfluxDB Token - where to find it?

### ISSUE THREAD

**Issue by maltokyo** [smilebasti/npmGrafStats#16]
Read all the installation docs, but I cant find where to get the influxdb token for this line in docker-compose file:

`INFLUX_TOKEN: '<replace>' # insert after first run and manual token creation`

Sorry for the stupid question, but where do I get this token?  I checked the logs, I could not find it in there after first run of influx..

**Comment by smilebasti** [comment]
Hi,
you need to login into the gui of influxdb and select Data source and then Token. There you will be able to create a write token for npmGrafStats and a read token for Grafana.

**Comment by maltokyo** [comment]
Thank you @smilebasti, will try this - just a hint, for people who have never used influxdb (and didnt even know it has a GUI), perhaps it would be good to add your comment above into the installation wiki.

**Comment by smilebasti** [comment]
Already did ;)

Will close this issue. If it persists you can reopen it.
