### ISSUE TITLE
Installed and everything working - Grafana has no dashboard - it is just default

### ISSUE THREAD

**Issue by maltokyo** [smilebasti/npmGrafStats#17]
Thank you for your help @smilebasti  with the Token, all worked well.

All docker-compose containers running, the token, and all user/passwords are set correctly.  But when I log in to grafana it is just a completely vanilla installation.  Should I not see your dashboard?  It is not clear what I now need to do.

What does smilebasti/npmgrafstats container actually do, it has no ports so I cannot connect to it...

Grafana screenshot - what to do now?

![image](https://github.com/smilebasti/npmGrafStats/assets/1388507/ed7e4fb0-774c-440d-ab5f-ea1d185fba84)

**Comment by maltokyo** [comment]
Ah, I had missed this..
https://github.com/smilebasti/npmGrafStats/wiki/Grafana-installation

Quite a bit of jumping around the docs to get it all working, not really a smooth experience reading the wiki and attempting step by step.  Just feedback.  It all works now, thank you!

**Comment by maltokyo** [comment]
Question remains, what does smilebasti/npmgrafstats container actually do?

**Comment by smilebasti** [comment]
Will work in the wiki.

First line oft the Readme: `This project analyzes the logs of the Nginx Proxy Manager and exports it to InfluxDB to be used in a Grafana Dashboard.`
