### ISSUE TITLE
platform: linux/arm64/v8

### ISSUE THREAD

**Issue by Geromiel** [smilebasti/npmGrafStats#19]
Docker compose error on Raspi4:
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /root/start.sh: exec format error

**Comment by smilebasti** [comment]
Hi, have you used `smilebasti/npmgrafstats:latest-arm`?

Need to add the tag options to the docker-compose.yml file.

Let me know if the arm tag works for you.

**Comment by Geromiel** [comment]
Works with this command. Funny because when using platform: linux/arm64/v8 in the docker-compose.yml it doesnt find the right image.

**Comment by smilebasti** [comment]
Great to hear.

In my ci it should use linux/arm/v8 but it's not added in Docker Hub (`docker-buildx build --platform linux/arm/v7,linux/arm64/v8`)
https://hub.docker.com/repository/docker/smilebasti/npmgrafstats/tags?page=1&ordering=last_updated
