### ISSUE TITLE
Stops Working after a few Days

### ISSUE THREAD

**Issue by smilebasti** [smilebasti/npmGrafStats#2]
Odd behavior that the image stops working after few days.
- logrotation?
- memory leak?

**Comment by smilebasti** [comment]
A workaround has come with v2.2.0.
Restarting the container now doesn't duplicate the logs.

You can create a cron job to restart npmgrafstats to avoid that the collection stops.

**Comment by smilebasti** [comment]
If somebody has any idea with this issue or can help please let me know :)

**Comment by G3VV** [comment]
Still no update on this? I'm having this issue now every 5 minutes.
Hit's slowly drop from their peak to "No Data", **this was fixed with a cron**.
What the cron does not fix is the spikes of hit's per minute due to each restart..
![image](https://github.com/smilebasti/npmGrafStats/assets/46306494/26525663-47d7-4528-a9fa-a8f7f1b00040)

**Comment by smilebasti** [comment]
@G3VV Sorry still not. Every 5 minutes seems to be too quick for my liking. In my use it happens about every 7 days with about 50 domains. The vm has for testing 4 GB Ram.
Can you share something about your system? Maybe i can narrow it down a bit better? Ram usage and number of domains?

I will have a look at the spikes.

**Comment by G3VV** [comment]
> @G3VV Sorry still not. Every 5 minutes seems to be too quick for my liking. In my use it happens about every 7 days with about 50 domains. The vm has for testing 4 GB Ram. Can you share something about your system? Maybe i can narrow it down a bit better? Ram usage and number of domains?
> 
> I will have a look at the spikes.

My proxy server is 8GB with 4 cores, i have 210 proxy hosts. 
About 5 minutes after restarting the npmgraf docker the "Hit's in the last 5 minutes" will drop to "No Data" along-side all other information ceasing to update? I've looked at logs on all services and nothing shows any errors?
![image](https://github.com/smilebasti/npmGrafStats/assets/46306494/6ee82445-79b0-4ace-a98a-29dfc5a801d5)
![image](https://github.com/smilebasti/npmGrafStats/assets/46306494/53c603d6-d2ea-40b1-b6a4-a15c84a1e8e8)

**Comment by bam91** [comment]
> You can create a cron job to restart npmgrafstats to avoid that the collection stops.

Is there a nice way to do so in Docker?

I have checked the code and thought about it. 
My first Idea: The problem could be in https://github.com/smilebasti/npmGrafStats/blob/main/Getipinfo.py#L122 . The Syncronus write would maye stop the whole process if Influxdb is not responding. 
Solution: Set some kind of timeout to this operation or make it async. Async would be easy to do (https://github.com/smilebasti/npmGrafStats/blob/main/Getipinfo.py#L95). Maybe you could try this and add it to the image.

**Comment by smilebasti** [comment]
@bam91 Thanks for the ideas. I will test them.

I am also currently testing if it's a problem with not closing the connection after the data is written to InfluxDB. Will update when something works.

**Comment by smilebasti** [comment]
Closing the connection to InfluxDB after the data was sent seemed to help. 

Now I had it stop working when the logs rotated. I will try `tail -F` instead of `tail -f`. That will be easier to test than the connection limit. 

If it works I can push a preview/test image with the fix in a couple of days.

**Comment by smilebasti** [comment]
I released v2.3.1. It should fix the need of restarting npmGrafStats.

Just pull the latest image and recreate npmGrafStats. Please let me know if we can close this issue :)


 @G3VV i haven't done anything about the spikes. Please also let me know if they persist.
