### ISSUE TITLE
Grafana v9 and maps

### ISSUE THREAD

**Issue by mtucker119** [smilebasti/npmGrafStats#20]
First of all, thank you for the work you did on this. It works great. 

One thing I noticed was that the maps don't work on version 9 of Grafana. I hadn't updated yet and I thought there was something wrong with the query. But when I looked at the data it was returning it looked it good. I already had Grafana installed and I figured adding the latest tag to the image and telling Portainer to always pull the image when re-deploying would be enough. But turns out the latest tag doesn't pull v10, I had to add the tag main instead. 

Just a heads up in case any one else runs into the same problem. We upgraded to v10 from v9 and didn't see any problems FWIW.

**Comment by smilebasti** [comment]
Thanks. Will test it and add a note to the wiki.

Is the whole Dashboard not working in Grafana v9 or just the Map?

**Comment by mtucker119** [comment]
It was just the map that wasn't working.

**Comment by mtucker119** [comment]
I just checked the old image and it was v9.2.5.
Thanks for checking. It was probably just something misconfigured on my old one.

**Comment by smilebasti** [comment]
Ok then i will close this issue now. Will further expand the wiki with your information. Thanks :)
