### ISSUE TITLE
Some domains not working and Map not working

### ISSUE THREAD

**Issue by maltokyo** [smilebasti/npmGrafStats#22]
I have several sites, eg:

a. xyz.domain.com
b. abc.domain.com
c. def.anotherdomain.com

and also just 

d. domain.com (same as www.domain.com).
e. anotherdomain.com (same as www.anotherdomain.com).

Everything works for a. and b. but not for any of the TLDs, only for subdomains it seems.  And for some other subdomains like c. it just isn't logging anything at all (can't see anything in the `docker-compose log -f` command when I visit those sites.

How can I check what is going on with these ones that are not working?

Also, the map is not working for anything, even though the log shows correctly the city names.

**Comment by smilebasti** [comment]
Hi, strange to hear.

As the domain is collected here: https://github.com/smilebasti/npmGrafStats/blob/bef7c55111e2fc7de1e75e36a63b4fa1dd6fee7e/sendips.sh#L24C4-L24C4, i can only think of if you maybe capitalized the domain? (Domain.com)

Are these TLD redirection or proxy hosts? Are you using IPv6?

Logging starts after a IPv4 is found in the logs.

Have you had a look at issue #21 for your map Problem?

**Comment by smilebasti** [comment]
@maltokyo, any update on your issue?

**Comment by maltokyo** [comment]
It's still not working, didn't have the time to work out why. Is there a private way I can share logs? Thank you

**Comment by smilebasti** [comment]
Upload them to some Pastebin and send the link or just everything to npmgrafstats@smilebasti.myhome-server.de.

Would be interesting to see which domains don't show up.

**Comment by smilebasti** [comment]
As i haven't received any info i will close this. You may reopen it when needed.
