### ISSUE TITLE
Support for multiple NPM instances

### ISSUE THREAD

**Issue by karthikvenkat123** [smilebasti/npmGrafStats#23]
Fantastic work and brilliant documentation. Had no issues getting it up and running for my NPM instance.

Feedback - it would be a nice to have feature if we can somehow ingest logs from two separate Npm instances. I run separate reverse proxies for my internal and external domains. The world map graph wouldn’t be much since all my internal domains would be from the same external Ip but the other statistics would be slick to see

**Comment by smilebasti** [comment]
Thanks. Glad to hear.

If you set the same bucket and influxdb host on both npmgrafstats, then you should be able to see everything in one dashboard. The current one has internal logs at the bottom. As internal ip's get saved in a different measurement name it should be easy to adjust the dashboard.

**Comment by smilebasti** [comment]
https://www.reddit.com/r/nginxproxymanager/comments/1418ae1/comment/jt4eoxo/?context=3
