### ISSUE TITLE
Map filter domain

### ISSUE THREAD

**Issue by Chrispikaan** [smilebasti/npmGrafStats#27]
Hi, i really like the map on the dashboard. But is there a way to filter on (sub)domain? Now all the IP's from all the (sub)domains are shown on the map, but I want to select which (sub)domains I see on the map.

Is this already possible? Or is this something you will maybe implement in the future?

**Comment by smilebasti** [comment]
Hi, i have thought about that feature.


The only way to implement this in Grafana is with variables in the dashboard settings. I haven't played around with it but will in the next days.


Maybe it's possible to restrict the variable to a row or just a specific panel. Will let you know.

**Comment by smilebasti** [comment]
It's working. I uploaded a revision to https://grafana.com/grafana/dashboards/18826-npm-map-influx-v2-3/. Download it and replace it with your current dashboard. I will push it to github when i tested the v2.3.2 release with a smaller base image.

Test it and let me know if it works as intended. If not reopen this issue.

**Comment by Chrispikaan** [comment]
It looks like it's working perfect. Thanks for your good an fast work! 👍
