### ISSUE TITLE
Exclude IP from dashboard ?

### ISSUE THREAD

**Issue by Chrispikaan** [smilebasti/npmGrafStats#28]
Hello, I really like your new feature that it's possible to filter domains on the dashboard.
But is it also possible to exclude IP's from showing up on the dashboard? 

The reason i'm asking this is that I have a monitoring server that is checking the uptime of my domains. But this ip shows up very much in the dashboard of course. 
Is there a way I can exclude it from showing up? Or is this a feature you need to implement first?
![afbeelding](https://github.com/smilebasti/npmGrafStats/assets/99992200/11945cb0-bae0-4508-bdb8-9e43f3a32a9b)

**Comment by smilebasti** [comment]
Hi, this is already implemented. See https://github.com/smilebasti/npmGrafStats/wiki/Installation#set-your-credentials-variables-and-directories point 6.
