### ISSUE TITLE
Add support for more domains names extensions (InfluxDB v1)

### ISSUE THREAD

**Issue by Matthis-F** [smilebasti/npmGrafStats#3]
Hi,
I am unable to get the domain name for a reverse proxy connection when the extension is something else than .com

After looking through the code I found that only some domains extensions are "supported"

According to the file ```sendips.sh```, only .com .de .net .org are catched:
```
  #Domain or subdomain gets found. only de/net/org/com
  domain=`echo ${line:0:80} | grep -m 1 -o -E "([a-z0-9\-]*\.){1,3}?[a-z0-9\-]*\.(de|net|org|com)"`
```
Would it be possible to support more domains names extensions ? 
Or add a way to customize this with an env variable in Docker ?

Thanks for all the good work you made on this project 👍

**Comment by Matthis-F** [comment]
Seems like it works on the InfluxV2 (main) version but was not implemented on the InfluxV1 branch.
Would it be possible to update it ?

**Comment by smilebasti** [comment]
Hi, thank you for noticing. Somehow missed it.

I pushed a change that should fix that. If it still persists just reopen this issue.

Enjoy :)
