### ISSUE TITLE
Can't seem to work with LePresidente/docker-nginx-proxy-manager

### ISSUE THREAD

**Issue by nickvin** [smilebasti/npmGrafStats#30]
I've been using this container, as per the suggested configuration, but wanted to switch out jc21/nginx-proxy-manager with LePresidente/docker-nginx-proxy-manager, given the added crowdsec features.
That container doesn't run the npm db (jc21/mariadb-aria) though.
Does that explain why it doesn't work, or is there something special that can be done to make it work?
From testing, I can determine that influxdb isn't receiving any log info, so the graphs are empty.

**Comment by smilebasti** [comment]
Hi,
npmGrafStats ingests the logs that are mounted as a volume in `volumes: - ./data:/data`. There is no need for database access.
I haven't found any documentation on this at LePresidente/docker-nginx-proxy-manager. 

Let me know if you get it work.

**Comment by nickvin** [comment]
I found the problem. The logs location is changed to /data/log instead of /data/logs for LePresidente/docker-nginx-proxy-manager. It tries to create a symlink when the container starts, but with certain file remnants it wasn't working properly.
Thanks for confirming the ingestion mechanism!
