### ISSUE TITLE
No Issue/More of a feature request

### ISSUE THREAD

**Issue by parsoli** [smilebasti/npmGrafStats#36]
Finally got this working and it's a much better way to visualize what's going on thru NPM.  WilliamDonze has a similar product he's come up with that provides some additional level of detail such as paths of URL's accessed, any status codes/errors, browser detail, etc....would be neat to pull this information in your tool.  Just a thought.  Thanks for putting this together!

https://medium.com/@williamdonze/grafana-monitor-nginx-proxy-manager-website-4d03b60c761f

**Comment by smilebasti** [comment]
Hi, interessting to hear of a similar solution.
I think that keeping the original software (NPM) as native as possible will make npmGrafStats more userfriendly.
You may fork it and try a implementation but to make it easier for others as a simple add-on, i will not change the log-format output.
Maybe changing to Promtail and Loki and away from the custom script currently used would be a option.
