### ISSUE TITLE
Allow/Block from country

### ISSUE THREAD

**Issue by javixuwi** [smilebasti/npmGrafStats#42]
Hi! perfect and working on first run! Congrats!
I want to know if there is a way as we have running npm and geoip, to configure npm for allow/blocking from country, and how we need to add that info to the grafana dashboard.

I was using this tutorial but it doesnt work anymore..: https://www.reddit.com/r/nginxproxymanager/comments/sjf1hw/tutorial_nginx_proxy_manager_together_with_geoip2/

It would be so complete on functions if we can make it work!

**Comment by smilebasti** [comment]
Hi, great to hear that its working on the first go.

NpmGrafStats not interfering with NPM and i am not going to modify NPM. It is just reading the logs and displaying the statistics for them.

So i don't think there is any way to make this work with NPMGrafStats.
