### ISSUE TITLE
new installation influx empty

### ISSUE THREAD

**Issue by manustars** [smilebasti/npmGrafStats#43]
Meanwhile, congratulations on the work, I followed the installation guide and everything seems ok, in the portainer log I see that it reads the NMP logs, but when I went to check influx, I see the bucket empty.

**Comment by smilebasti** [comment]
Hi, thank you.

Do you see `*** Data send ***` after Measurement Time?

**Comment by manustars** [comment]
i don't see `*** Data send ***`.

i can set measurement time? the container runing arout 5 hours

**Comment by smilebasti** [comment]
Ok. The logs should look like:
```
**************** start *********************
Measurement-name: ReverseProxyConnections
United States
New York
New York
10013
-74.0
40.7157
US
Clouvider Limited
Outside IP:  194.33.ch.ch
Target IP:  192.168.ch.ch
Domain:  support.domain.de
Measurement Time:  2024-04-04T05:16:11+00:00
*************** data send ******************
```

**Comment by manustars** [comment]
i see this log
`npmGrafStats: v2.4.1
Startup: lets get the logs send them to influx
Only Reverse-Proxy Logs activated
Your external IP is: 
Internal IP-Source: 10.0.1.5 called: ha.mydomain.com
Internal IP-Source: 10.0.1.5 called: ha.mydomain.com
Internal IP-Source: 10.0.1.5 called: ha.mydomain.com
Internal IP-Source: 10.0.1.5 called: ha.mydomain.com
Internal IP-Source: 10.0.1.5 called: ha.mydomain.com
Internal IP-Source: 10.0.1.5 called: ha.mydomain.com
Internal IP-Source: 10.0.1.5 called: ha.mydomain.com
Internal IP-Source: 10.0.1.5 called: ha.mydomain.com
Internal IP-Source: 10.0.1.5 called: ha.mydomain.com
Internal IP-Source: 10.0.1.5 called: ha.mydomain.com
Internal IP-Source: 10.0.1.99 called: cloud.mydomain.com
Internal IP-Source: 10.0.1.5 called: cloud.mydomain.com
Internal IP-Source: 10.0.1.99 called: cloud.mydomain.com
Internal IP-Source: 10.0.1.99 called: cloud.mydomain.com
Internal IP-Source: 10.0.1.99 called: cloud.mydomain.com
Internal IP-Source: 10.0.1.99 called: cloud.mydomain.com
Internal IP-Source: 10.0.1.5 called: cloud.mydomain.com
Internal IP-Source: 10.0.1.99 called: cloud.mydomain.com
Internal IP-Source: 10.0.1.99 called: cloud.mydomain.com
Internal IP-Source: 10.0.1.99 called: cloud.mydomain.com
Internal IP-Source: 192.168.30.254 called: stream.mydomain.com
Internal IP-Source: 192.168.30.254 called: stream.mydomain.com
Internal IP-Source: 192.168.30.254 called: stream.mydomain.com
Internal IP-Source: 192.168.30.254 called: stream.mydomain.com
Internal IP-Source: 192.168.30.254 called: stream.mydomain.com
Internal IP-Source: 192.168.30.254 called: stream.mydomain.com
Internal IP-Source: 192.168.30.254 called: stream.mydomain.com
Internal IP-Source: 192.168.30.254 called: stream.mydomain.com
Internal IP-Source: 192.168.30.254 called: stream.mydomain.com
Internal IP-Source: 192.168.30.254 called: stream.mydomain.com`

i run curl -s ifconfig.me/ip on docker consolle (portainer) but non see any output

and this my compose
`version: '3'
services:
  npmgraf:
    image: smilebasti/npmgrafstats
    container_name: npmstats
    environment:
      - INFLUX_HOST=10.0.1.251:8686  # use host IP
      - INFLUX_BUCKET=npmgrafstats
      - INFLUX_ORG=Home
      - INFLUX_TOKEN=mytoken
      - REDIRECTION_LOGS=true # set to TRUE or FALSE or ONLY
      - INTERNAL_LOGS=false # set to TRUE or FALSE or ONLY # IMPORTANT see below for more info about this feature
      - MONITORING_LOGS=false # set to TRUE or FALSE or ONLY # IMPORTANT see below for more info about this feature
    volumes:
      - /home/rancher/NPM/data/logs:/logs
      - /home/rancher/GEOLITE:/geolite`

**Comment by smilebasti** [comment]
The logs only include private IPs.
Please test setting `INTERNAL_LOGS=TRUE`.

**Comment by manustars** [comment]
I'm starting to wonder if it's key sensitive, don't want 'true' but 'TRUE'. now the dashboard seems to be working, my map is completely empty and I don't know if it reads my public IP correctly

**Comment by smilebasti** [comment]
Yes it is case-sensitive. (maybe we should change that :)).

Can you please check your npm logs if there are other ip's then private ones (10...., 192.168... or 172.16-32...)? 
If yes, i need to check and implement a different way to get the external ip.

**Comment by manustars** [comment]
I probably won't see the traffic coming from outside, I have a slightly different configuration. I am listening to port 443 on WAN for the VPN is in the VPN server I have the portshare that forwards non-VPN traffic to npm in DMZ, so the traffic is internal

**Comment by smilebasti** [comment]
Ok interesting setup.

So no map is shown. You can try to forward the external ip.

But as it now seems to work i will close this issue.
