### ISSUE TITLE
Ability to exclude subnets

### ISSUE THREAD

**Issue by pittbull** [smilebasti/npmGrafStats#45]
Hi, just found your tool and must say I allready love it very much. Thank you for the effort.

One question on exclusions: is it much work to enable CIDR notation in the monitoringips.txt file? I am frequently accessing my services via proxy services (work enforced), and I would like to be able to exclude entire subnets.

**Comment by smilebasti** [comment]
Hi, great to hear.

Currently, the monitoringips.txt gets the ips with https://github.com/smilebasti/npmGrafStats/blob/42e8a3661f07e97da167b903770b5cf1964d1f3b/sendips.sh#L58. This is just a simple comparison for the same IP. This would require a rewrite of that logic. Currently, i don't have the time for that.
You are welcome to open am Pull request if you know how to implement such thing.

I will leave this issue open for the future and my todo list.

**Comment by pittbull** [comment]
Appreciate the lack of time on your part. I've done some searching and there exists command 'grepcidr' which looked to solve my problem.

Unfortunately the official package does not solve my problem, but there exists a forked version 3 [here](https://github.com/ryantig/grepcidr) which does. Any chance you could update the image with this command?

If so I can create a PR which would add the possibility to use CIDR as well.

**Comment by pittbull** [comment]
Compiled the linked package on another machine and made it available to the image. Confirming that the following command will identify the ip both if specified as an ip and in cidr notation:

`grepcidr -D ip monitoringips.txt`

**Comment by pittbull** [comment]
> Compiled the linked package on another machine and made it available to the image. Confirming that the following command will identify the ip both if specified as an ip and in cidr notation:
> 
> `grepcidr -D ip monitoringips.txt`

- Cloned your reposity locally
- Added [grepcidr](https://github.com/ryantig/grepcidr)
- Changed sendips.sh line 59 to: `elif grepcidr -D $outsideip ./monitoringips.txt >> /dev/nul` 
- Rebuild image

Success!

**Comment by pittbull** [comment]
No worries - not an expert myself. Perhaps I got lucky, but I downloaded it to a temp folder and entered into it and ran "build". 

I then edoted your Dockerfile adding a COPY command for the grepcidr file.

**Comment by smilebasti** [comment]
> No worries - not an expert myself. Perhaps I got lucky, but I downloaded it to a temp folder on my server and entered into it and ran "build".
> 
> Copy the grepcidr file to the folder with your Dockerfile and add the following to it:
> 
> `COPY grepcidr /usr/local/bin/grepcidr
> 
> RUN chmod +x /usr/local/bin/grepcidr`

Thanks. Got it to work. Will release it in the coming days.
