### ISSUE TITLE
Support Nginx installed by apt on Debian system

### ISSUE THREAD

**Issue by kekylin** [smilebasti/npmGrafStats#46]
This is a great project, thank you for your contribution, thank you!

Have you considered supporting Nginx installed via apt on Debian? I have tried to find similar projects to record my website access history, but I didn't find a more suitable project than this one, so I came to ask.

Projects based on Grafana+Loki+Promtail can also read Nginx logs to display website access records. I built it based on the following project and used it for a while, but it has many problems that have been bothering me, causing me to not be able to use it well. After comprehensive comparison, I still think that the npmGrafStats project is better.

Project address: https://grafana.com/grafana/dashboards/12559-loki-nginx-service-mesh-json-version/

English is not my native language, I explained it through Google Translate, please forgive me.

Thank you! Looking forward to your reply.

**Comment by smilebasti** [comment]
Hi, i thought about it.
The problem i see is the custom nginx log config. Not sure how to move around this or if it should just support nginx default?

I haven't yet but wanted to test the Grafana+Loki+Promtail Stack as an alternative. What were your Problems?
